### ISSUE TITLE
Spaces missing in if statement on Ubuntu script.

### ISSUE THREAD

**Issue by SirToffski** [bmfmancini/cacti-install-wizard#1]
Line 95 if statement:
`if [$timezone = ""] `

Space is needed before/after:
`if [ $timezone = "" ] `

Edit:
Also same with lines: 113, 127, 273

Good work btw.

**Comment by bmfmancini** [comment]
Thanks for the find !

**Comment by bmfmancini** [comment]
See newest commit with the changes added
