### ISSUE TITLE
Graphs not filling full window.

### ISSUE THREAD

**Issue by shakey1** [bmfmancini/cacti-install-wizard#10]
The setup completed successfully, but the graphs are not being displayed fully.  They begin and stay roughly at the 19:00 mark.
![Graphs](https://user-images.githubusercontent.com/10562402/63312604-e4cd3180-c2b6-11e9-8fcc-0a5ec494d33c.PNG)

I tried deleting the graphs and data sources and recreating them, but I am seeing the same behavior.  Any idea's on what may be causing this?  This is running on an Ubuntu guest on a VMWare ESXI server.

**Comment by bmfmancini** [comment]
Are you using spine ?
Do you have any errors in the cacti log ?
Are you still using the default 5 minute polling that the script puts in the cron ?

**Comment by bmfmancini** [comment]
Also make sure your php  timezone is correct

**Comment by shakey1** [comment]
I am using Spine.  I set the logging to debug and nothing jumped out at me as an obvious cause, but I'll double check both that and the time zone.  Polling is set to the 5 minute default.

**Comment by shakey1** [comment]
The time zone is set properly as "date.timezone = America/Los_Angeles".  I'll report back on the logs after a few polling cycles.
