### ISSUE TITLE
Can't Login

### ISSUE THREAD

**Issue by bkbristlin** [bmfmancini/cacti-install-wizard#17]
I ran a new install today and can't login to the GUI. I tried to reset the password for "admin" in the DB and still no luck. Also copied the MD5 hash from the DB and verified it is actually set to "admin" after the change.

Ubuntu 18.04 LTS
Cacti 1.2.10

**Comment by bmfmancini** [comment]
Interesting

can you do a tail pn /var/www/html/cacti/log/cacti.log 
try to login and see what the output is for login failure

**Comment by bkbristlin** [comment]
I can't remember which test VM it was. I'll re-deploy it and add the results soon. I was able to get 1.2.9 going fine so I think it's related to the version.

Also some things I noticed when running the script:
- It would be helpful to change repos to 'Universe' prior to running, I got a lot of package failures. 
- There is an issue during the Cacti install with mysql unicode version, I found a fix for that I can post. 
- I told the installer to add Spine, during the install I saw some errors about not being able to chown because the directory didn't exist. I'll try and save the output from the 1.2.10 install so you can see the messages.

Great script by the way!! Really simplified a lot of the issues I've seen with doing this piece by piece. I've had 1.2.9 running great with 1m polling intervals since yesterday evening.

**Comment by bmfmancini** [comment]
ok thanks for the report !

Please share what you found and if you'd like the fix would be cool too 

thanks !

**Comment by bkbristlin** [comment]
Here's the log output. Also of note there are no graphics like 1.2.9 has on the login page and the login text and boxes are in the top left corner instead of centered. I saved the output from the install too if that is helpful. Not sure how to attach it here.

`brian@ubuntu-18-lts-template:~/cacti-auto-install$ tail pn /var/www/html/cacti/log/cacti.log
tail: cannot open 'pn' for reading: No such file or directory
==> /var/www/html/cacti/log/cacti.log <==
04/02/2020 10:24:15 - CMDPHP ERROR: A DB Row Failed!, Error: MySQL server has gone away
04/02/2020 10:24:15 - CMDPHP SQL Backtrace:  (/poller.php[689]:process_poller_output(), /lib/poller.php[417]:db_fetch_assoc(), /lib/database.php[473]:db_fetch_assoc_prepared(), /lib/database.php[487]:db_execute_prepared())
04/02/2020 10:24:15 - CMDPHP ERROR: A DB Row Failed!, Error: MySQL server has gone away
04/02/2020 10:24:15 - CMDPHP SQL Backtrace:  (/poller.php[689]:process_poller_output(), /lib/poller.php[421]:db_fetch_assoc_prepared(), /lib/database.php[487]:db_execute_prepared())
04/02/2020 10:24:16 - CMDPHP ERROR: A DB Cell Failed!, Error: MySQL server has gone away
04/02/2020 10:24:16 - CMDPHP SQL Backtrace:  (/poller.php[664]:db_fetch_cell_prepared(), /lib/database.php[399]:db_execute_prepared())
04/02/2020 10:24:16 - CMDPHP ERROR: A DB Row Failed!, Error: MySQL server has gone away
04/02/2020 10:24:16 - CMDPHP SQL Backtrace:  (/poller.php[689]:process_poller_output(), /lib/poller.php[417]:db_fetch_assoc(), /lib/database.php[473]:db_fetch_assoc_prepared(), /lib/database.php[487]:db_execute_prepared())
04/02/2020 10:24:16 - CMDPHP ERROR: A DB Row Failed!, Error: MySQL server has gone away
04/02/2020 10:24:16 - CMDPHP SQL Backtrace:  (/poller.php[689]:process_poller_output(), /lib/poller.php[421]:db_fetch_assoc_prepared(), /lib/database.php[487]:db_execute_prepared())
brian@ubuntu-18-lts-template:~/cacti-auto-install$
`

**Comment by bkbristlin** [comment]
Oh one other thing I noticed in 1.2.9. You can't adjust the theme after install. I can choose anyone and save it but the theme doesn't actually change.

**Comment by bkbristlin** [comment]
This is the mysql fix.

Edit 50-server.cnf and change the collation-server from utf8mb4_general_ci to utf8mb4_unicode_ci

>brian@ubuntu-18-lts-template:/etc/mysql/mariadb.conf.d$ ls
50-client.cnf  50-mysql-clients.cnf  50-mysqld_safe.cnf  50-server.cnf

**Comment by bmfmancini** [comment]
ah yea I see now I need to put the logic for sed to add the utf8mb4 settings under mysqld 
ok cool thanks a lot for the report !
