### ISSUE TITLE
stop install on centos 7

### ISSUE THREAD

**Issue by alsyundawy** [bmfmancini/cacti-install-wizard#20]
hi, i get stop install after install git

this script requires git
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: mirror.biznetgio.com
 * epel: d2lzkl7pfhq30w.cloudfront.net
 * extras: vpsmurah.jagoanhosting.com
 * updates: mirror.biznetgio.com
Package git-1.8.3.1-23.el7_8.x86_64 already installed and latest version
Nothing to do
1) New-installation         
2) spine-only-installation 
3) cacti-upgrade
4) Remote Poller Setup
 5) Quit
#?
[root@webserver ~]#

**Comment by bmfmancini** [comment]
Hey There 

which option did you choose once and where did it get stuck ?
thanks !

**Comment by alsyundawy** [comment]
please try your self, script not runing & stop after asking this

1) New-installation         
2) spine-only-installation 
3) cacti-upgrade
4) Remote Poller Setup
 5) Quit
#?


I can't choose when the question option appears because the script doesn't run and stops itself

**Comment by bmfmancini** [comment]
Interesting I will check

**Comment by bmfmancini** [comment]
This is what I am seeing on a fresh centos 7 droplet

Dependency Installed:
  perl-Error.noarch 1:0.17020-2.el7              perl-Git.noarch 0:1.8.3.1-23.el7_8              perl-TermReadKey.x86_64 0:2.30-20.el7              rsync.x86_64 0:3.1.2-10.el7

Complete!
1) New-installation         4) Remote Poller Setup
2) spine-only-installation  5) Quit
3) cacti-upgrade
#? 1
This script will download all Cacti dependecies and download the chosen cacti version from the cacti github
Dont forget to support cacti @ cacti.net!
set selinux to disabled
here are some of the current cacti release versions
1.2.16
1.2.17
1.2.2
1.2.3
1.2.4
1.2.5
1.2.6
1.2.7
1.2.8
1.2.9
which release would you like to download ? Hit enter for latest
^C
[root@li1981-51 ~]# cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)
[root@li1981-51 ~]#

we can do a troubleshooting session together if you would like 
Please reach out to me via email we can set something up
