### ISSUE TITLE
Secure password should be used

### ISSUE THREAD

**Issue by netniV** [bmfmancini/cacti-install-wizard#7]
https://github.com/bmfmancini/cacti-install-wizard/blob/500202c08a2130105b261e510898876fbd641c90/cacti-setup-wizard-debian-Ubuntu.sh#L204

You should ensure that you auto-generate a password for the system so that the database password is not easily guessable.

**Comment by bmfmancini** [comment]
Thank you sir ! good point I will work on that

**Comment by bmfmancini** [comment]
Updated the script and tested for Centos using openssl to generate a random base 64 password
Working on the ubuntu side now

**Comment by bmfmancini** [comment]
Updated the Ubuntu script closing this
